application:
  bucket-name: testbucket
  enable-server-side-encryption: true
  server-side-encryption-algorithm: AES256
  enable-versioning: true

spring:
  cloud:
    aws:
      endpoint: http://127.0.0.1:4566
      credentials:
        access-key: noop
        secret-key: noop
      region:
        static: us-east-1
  data:
    jpa.repositories.bootstrap-mode: deferred
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          lob:
            non_contextual_creation: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  threads:
    virtual:
      enabled: true

management:
  endpoints.web.exposure.include: configprops,env,health,info,logfile,loggers,metrics,prometheus,sbom
  endpoint.health.show-details: always

logging:
  level:
    software:
      amazon:
        awssdk:
          regions:
            internal:
              util: ERROR
