version: '3.8'
services:

  localstack:
    image: localstack/localstack:4.7.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis, dynamodb, iam
      - DEFAULT_REGION=us-east-1
    volumes:
      - "../.localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook

volumes:
  localstack:
