version: '3.8'
services:

  localstack:
    image: localstack/localstack:4.9.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_CBOR_DISABLE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../.localstack:/etc/localstack/init/ready.d"  # ready hook
