version: '3.8'
services:
  localstack:
    image: localstack/localstack:4.9.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ses
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
